/**
 * ═══════════════════════════════════════════════════════════════
 *   PHOSPHOR ICON MAP — Reliv AI
 *   Maps every emoji marker to its Phosphor icon replacement.
 *   Import icons from '@phosphor-icons/react'
 * ═══════════════════════════════════════════════════════════════
 */

import {
    // Navigation & Actions
    House,
    ArrowLeft,
    Rocket,
    Sparkle,
    CheckCircle,
    XCircle,
    Check,
    Checks,
    Warning,
    ArrowsClockwise,
    Link,
    ClipboardText,

    // Health & Fitness
    Barbell,
    PersonSimpleRun,
    SwimmingPool,
    Bicycle,
    PersonSimpleThrow,
    Lightning,
    Fire,
    Snowflake,
    HandHeart,
    Medal,
    SoccerBall,
    Target,
    ChartBar,
    TrendUp,
    TrendDown,

    // Food & Meals
    CookingPot,
    Bowl,
    ForkKnife,
    Orange,
    Leaf,
    Egg,
    Plant,
    Wine,
    Grains,
    Coffee,
    Pizza,
    Hamburger,

    // Water & Hydration
    Drop,
    DropHalf,

    // Sleep & Time
    Moon,
    SunHorizon,
    Timer,
    Bed,
    CloudMoon,
    Alarm,

    // Skin & Acne
    Circle,
    CircleHalf,
    Palette,
    FirstAid,
    Pill,
    Syringe,
    Sun,
    Jar,
    Asterisk,
    HandPalm,
    Hand,

    // Communication
    DeviceMobileCamera,
    ChatCircle,
    Phone,
    Envelope,
    Robot,
    HandWaving,
    ThumbsUp,
    ThumbsDown,
    User,
    Users,
    UsersThree,
    UsersFour,

    // Payment & Security
    CreditCard,
    CurrencyCircleDollar,
    Lock,
    LockKey,
    Shield,
    ShieldCheck,

    // Codes & Access
    Key,
    LockOpen,
    Password,

    // Celebrations & Success
    Confetti,
    Gift,
    MusicNotes,
    MusicNote,
    Trophy,
    MedalMilitary,
    Diamond,
    Crown,
    Star,
    Cake,

    // Emotions & Faces
    Smiley,
    SmileyWink,
    SmileyMeh,
    SmileyAngry,
    SmileyXEyes,
    SmileyNervous,
    SmileySad,

    // Plans & Features
    // CrystalBall not in Phosphor, using Eye instead
    CalendarBlank,
    Notepad,
    PushPin,
    Megaphone,
    ListChecks,

    // IoT Bot
    Bell,
    SpeakerHigh,
    SpeakerSimpleHigh,
    Microphone,
    Cursor,
    GameController,
    Monitor,
    Lightbulb,
    Package,
    Plug,
    Desktop,
    Heart,
    GearSix,
    PencilSimple,
    Wrench,
    Footprints,

    // Celebrity related
    FilmScript,
    FilmSlate,

    // Misc
    Flag,
    Camera,
    BeerStein,
    Buildings,
    WifiHigh,
    WifiSlash,
    Brain,
    FloppyDisk,
    Repeat,
    Question,
    GlobeHemisphereWest,
    Cat,
    Dog,
    Eye,
    Upload,
    Image,
    Trash,
    StopCircle,
    VideoCamera,
    Volleyball,
    HandFist,
    Shuffle,
    Broom,
    Bank,
    Heartbeat,
    Prohibit,
    BookOpen,
    GraduationCap,
    ChatCenteredDots,
    Stethoscope,
    MagnifyingGlass,
    Waves,
    Bicycle as Cycle,
    Scales,
    UsersFour as Family,
    Chalkboard,
} from '@phosphor-icons/react';


/**
 * Master mapping: emojiMarker → { icon: PhosphorComponent, weight }
 * weight: 'regular' | 'bold' | 'fill' | 'duotone' | 'thin' | 'light'
 */
const phosphorIconMap = {

    // ═══ NAVIGATION & ACTIONS ═══
    home: { icon: House, weight: 'fill' },
    back: { icon: ArrowLeft, weight: 'bold' },
    launch: { icon: Rocket, weight: 'fill' },
    sparkle: { icon: Sparkle, weight: 'fill' },
    check_circle: { icon: CheckCircle, weight: 'fill' },
    cross: { icon: XCircle, weight: 'fill' },
    check: { icon: Check, weight: 'bold' },
    double_check: { icon: Checks, weight: 'bold' },
    warning: { icon: Warning, weight: 'fill' },
    refresh: { icon: ArrowsClockwise, weight: 'bold' },
    link: { icon: Link, weight: 'bold' },
    clipboard: { icon: ClipboardText, weight: 'duotone' },

    // ═══ HEALTH & FITNESS ═══
    muscle: { icon: Barbell, weight: 'fill' },
    weightlifting: { icon: Barbell, weight: 'fill' },
    swimming: { icon: SwimmingPool, weight: 'fill' },
    running: { icon: PersonSimpleRun, weight: 'fill' },
    cycling: { icon: Bicycle, weight: 'fill' },
    yoga: { icon: PersonSimpleThrow, weight: 'fill' },
    boxing: { icon: HandFist, weight: 'fill' },
    lightning: { icon: Lightning, weight: 'fill' },
    fire: { icon: Fire, weight: 'fill' },
    snowflake: { icon: Snowflake, weight: 'regular' },
    massage: { icon: HandHeart, weight: 'fill' },
    medal_sports: { icon: Medal, weight: 'fill' },
    football: { icon: SoccerBall, weight: 'fill' },
    target: { icon: Target, weight: 'fill' },
    bar_chart: { icon: ChartBar, weight: 'fill' },
    chart_up: { icon: TrendUp, weight: 'bold' },
    chart_down: { icon: TrendDown, weight: 'bold' },
    person_lifting: { icon: Barbell, weight: 'fill' },

    // ═══ FOOD & MEALS ═══
    breakfast_egg: { icon: CookingPot, weight: 'fill' },
    lunch_bowl: { icon: Bowl, weight: 'fill' },
    dinner_plate: { icon: ForkKnife, weight: 'fill' },
    banana: { icon: Orange, weight: 'fill' },
    fruit: { icon: Orange, weight: 'fill' },
    salad: { icon: Leaf, weight: 'fill' },
    chicken: { icon: ForkKnife, weight: 'fill' },
    egg: { icon: Egg, weight: 'fill' },
    plant: { icon: Plant, weight: 'fill' },
    milk: { icon: Wine, weight: 'fill' },
    nuts: { icon: Grains, weight: 'fill' },
    drink: { icon: Coffee, weight: 'fill' },
    plate_cutlery: { icon: ForkKnife, weight: 'duotone' },
    pizza: { icon: Pizza, weight: 'fill' },
    burger: { icon: Hamburger, weight: 'fill' },
    steak: { icon: ForkKnife, weight: 'fill' },
    apple: { icon: Orange, weight: 'fill' },
    avocado: { icon: Leaf, weight: 'fill' },
    juice: { icon: Coffee, weight: 'fill' },
    chocolate: { icon: Cookie, weight: 'fill' },

    // ═══ WATER & HYDRATION ═══
    water_drop: { icon: Drop, weight: 'fill' },
    water_tap: { icon: DropHalf, weight: 'fill' },

    // ═══ SLEEP & TIME ═══
    sleeping: { icon: CloudMoon, weight: 'fill' },
    sunrise: { icon: SunHorizon, weight: 'fill' },
    moon: { icon: Moon, weight: 'fill' },
    timer: { icon: Timer, weight: 'fill' },
    bed: { icon: Bed, weight: 'fill' },

    // ═══ SKIN & ACNE ═══
    red_circle: { icon: Circle, weight: 'fill' },
    black_circle: { icon: Circle, weight: 'fill' },
    white_circle: { icon: CircleHalf, weight: 'regular' },
    brown_circle: { icon: Circle, weight: 'fill' },
    desert: { icon: Sun, weight: 'duotone' },
    mixed_type: { icon: Palette, weight: 'fill' },
    lotion: { icon: Jar, weight: 'fill' },
    soap: { icon: Drop, weight: 'fill' },
    pill: { icon: Pill, weight: 'fill' },
    syringe: { icon: Syringe, weight: 'fill' },
    injection: { icon: Syringe, weight: 'fill' },
    sun: { icon: Sun, weight: 'fill' },
    honey: { icon: Jar, weight: 'fill' },
    eight_star: { icon: Asterisk, weight: 'bold' },
    lips: { icon: Drop, weight: 'fill' },
    hand_stop: { icon: HandPalm, weight: 'fill' },
    raised_hand: { icon: Hand, weight: 'fill' },
    bubbles: { icon: Drop, weight: 'duotone' },
    nail_polish: { icon: Sparkle, weight: 'fill' },
    stethoscope: { icon: Stethoscope, weight: 'fill' },
    microscope: { icon: MagnifyingGlass, weight: 'fill' },
    palette: { icon: Palette, weight: 'fill' },

    // ═══ COMMUNICATION ═══
    phone: { icon: DeviceMobileCamera, weight: 'fill' },
    chat_bubble: { icon: ChatCircle, weight: 'fill' },
    phone_call: { icon: Phone, weight: 'fill' },
    email: { icon: Envelope, weight: 'fill' },
    robot: { icon: Robot, weight: 'fill' },
    wave: { icon: HandWaving, weight: 'fill' },
    thumbs_up: { icon: ThumbsUp, weight: 'fill' },
    thumbs_down: { icon: ThumbsDown, weight: 'fill' },
    user: { icon: User, weight: 'fill' },
    users_group: { icon: Users, weight: 'fill' },
    couple: { icon: Users, weight: 'fill' },
    speaking_head: { icon: Microphone, weight: 'fill' },

    // ═══ PAYMENT & SECURITY ═══
    credit_card: { icon: CreditCard, weight: 'fill' },
    money_bag: { icon: CurrencyCircleDollar, weight: 'fill' },
    lock: { icon: Lock, weight: 'fill' },
    locked_key: { icon: LockKey, weight: 'fill' },
    shield: { icon: ShieldCheck, weight: 'fill' },

    // ═══ CODES & ACCESS ═══
    key: { icon: Key, weight: 'fill' },
    unlock: { icon: LockOpen, weight: 'fill' },

    // ═══ CELEBRATIONS & SUCCESS ═══
    party: { icon: Confetti, weight: 'fill' },
    gift: { icon: Gift, weight: 'fill' },
    confetti: { icon: Confetti, weight: 'fill' },
    birthday_cake: { icon: Cake, weight: 'fill' },
    music_notes: { icon: MusicNotes, weight: 'fill' },
    music_note: { icon: MusicNote, weight: 'fill' },
    trophy: { icon: Trophy, weight: 'fill' },
    trophy_cup: { icon: Trophy, weight: 'fill' },
    gold_medal: { icon: MedalMilitary, weight: 'fill' },
    silver_medal: { icon: MedalMilitary, weight: 'regular' },
    bronze_medal: { icon: MedalMilitary, weight: 'duotone' },
    sports_medal: { icon: Medal, weight: 'fill' },
    diamond: { icon: Diamond, weight: 'fill' },

    // ═══ EMOTIONS & FACES ═══
    smile: { icon: Smiley, weight: 'fill' },
    grin: { icon: SmileyWink, weight: 'fill' },
    relieved: { icon: SmileyMeh, weight: 'fill' },
    angry: { icon: SmileyAngry, weight: 'fill' },
    frustrated: { icon: SmileyAngry, weight: 'fill' },
    devil: { icon: SmileyXEyes, weight: 'fill' },
    sad: { icon: SmileySad, weight: 'fill' },
    thinking: { icon: SmileyNervous, weight: 'fill' },
    kiss: { icon: Heart, weight: 'fill' },
    slight_smile: { icon: Smiley, weight: 'regular' },
    raised_hands: { icon: HandWaving, weight: 'fill' },

    // ═══ PLANS & FEATURES ═══
    crown: { icon: Crown, weight: 'fill' },
    crystal_ball: { icon: Eye, weight: 'fill' },
    calendar: { icon: CalendarBlank, weight: 'fill' },
    notepad: { icon: Notepad, weight: 'fill' },
    pin: { icon: PushPin, weight: 'fill' },
    megaphone: { icon: Megaphone, weight: 'fill' },
    book: { icon: BookOpen, weight: 'fill' },
    books: { icon: BookOpen, weight: 'fill' },
    page: { icon: Notepad, weight: 'regular' },
    tear_calendar: { icon: CalendarBlank, weight: 'fill' },
    document: { icon: ClipboardText, weight: 'fill' },

    // ═══ IOT BOT ═══
    bell: { icon: Bell, weight: 'fill' },
    speaker: { icon: SpeakerHigh, weight: 'fill' },
    loud_speaker: { icon: SpeakerSimpleHigh, weight: 'fill' },
    pager: { icon: Desktop, weight: 'fill' },
    microphone: { icon: Microphone, weight: 'fill' },
    touch: { icon: Cursor, weight: 'fill' },
    game_controller: { icon: GameController, weight: 'fill' },
    laptop: { icon: Monitor, weight: 'fill' },
    lightbulb: { icon: Lightbulb, weight: 'fill' },
    star: { icon: Star, weight: 'fill' },
    package: { icon: Package, weight: 'fill' },
    plug: { icon: Plug, weight: 'fill' },
    screen: { icon: Desktop, weight: 'fill' },
    green_heart: { icon: Heart, weight: 'fill' },
    green_circle: { icon: Circle, weight: 'fill' },
    wrench: { icon: Wrench, weight: 'fill' },
    gear: { icon: GearSix, weight: 'fill' },
    pencil: { icon: PencilSimple, weight: 'fill' },
    theater_masks: { icon: Smiley, weight: 'duotone' },

    // ═══ CELEBRITIES ═══
    goat_messi: { icon: Trophy, weight: 'fill' },
    star_glow: { icon: Star, weight: 'fill' },
    microphone_celeb: { icon: Microphone, weight: 'fill' },
    musical_score: { icon: MusicNotes, weight: 'fill' },
    prince: { icon: Crown, weight: 'fill' },
    clapperboard: { icon: FilmSlate, weight: 'fill' },
    cricket_bat: { icon: Medal, weight: 'fill' },
    martial_arts: { icon: HandFist, weight: 'fill' },

    // ═══ FRIEND & COUPLE ═══
    couple_heart: { icon: Users, weight: 'fill' },
    cook_together: { icon: CookingPot, weight: 'fill' },
    walking: { icon: Footprints, weight: 'fill' },
    hot_pot: { icon: Bowl, weight: 'fill' },
    ok_hand: { icon: Check, weight: 'bold' },
    two_hearts: { icon: Heart, weight: 'fill' },
    group_2_friends: { icon: UsersThree, weight: 'fill' },
    group_3_friends: { icon: UsersFour, weight: 'fill' },
    group_4_friends: { icon: UsersFour, weight: 'fill' },

    // ═══ MISC ═══
    india_flag: { icon: Flag, weight: 'fill' },
    camera: { icon: Camera, weight: 'fill' },
    camera_old: { icon: Camera, weight: 'fill' },
    coffee: { icon: Coffee, weight: 'fill' },
    smiling_face: { icon: Smiley, weight: 'fill' },
    satellite: { icon: WifiHigh, weight: 'bold' },
    signal: { icon: WifiSlash, weight: 'bold' },
    zzz: { icon: CloudMoon, weight: 'fill' },
    building: { icon: Buildings, weight: 'fill' },
    bank: { icon: Bank, weight: 'fill' },
    hearts_revolving: { icon: Heart, weight: 'fill' },
    brain: { icon: Brain, weight: 'fill' },
    floppy_disk: { icon: FloppyDisk, weight: 'fill' },
    repeat: { icon: Repeat, weight: 'bold' },
    question: { icon: Question, weight: 'bold' },
    formula_car: { icon: Lightning, weight: 'fill' },
    cat: { icon: Cat, weight: 'fill' },
    dog: { icon: Dog, weight: 'fill' },
    panda: { icon: Smiley, weight: 'fill' },
    bunny: { icon: Smiley, weight: 'fill' },
    bear: { icon: Smiley, weight: 'fill' },
    purple_heart: { icon: Heart, weight: 'fill' },
    upload: { icon: Upload, weight: 'bold' },
    framed_picture: { icon: Image, weight: 'fill' },
    trash: { icon: Trash, weight: 'fill' },
    stop_sign: { icon: StopCircle, weight: 'fill' },
    video_camera: { icon: VideoCamera, weight: 'fill' },
    video_recorder: { icon: VideoCamera, weight: 'fill' },
    clapping: { icon: HandWaving, weight: 'fill' },
    facepalm: { icon: Warning, weight: 'fill' },
    gift_heart: { icon: Gift, weight: 'fill' },
    ribbon: { icon: Heart, weight: 'fill' },
    castle: { icon: Crown, weight: 'fill' },
    wave_water: { icon: Waves, weight: 'fill' },
    eyes: { icon: Eye, weight: 'fill' },
    graduation_cap: { icon: GraduationCap, weight: 'fill' },
    postbox: { icon: ChatCenteredDots, weight: 'fill' },
    exclamation: { icon: Warning, weight: 'fill' },
    shuffle: { icon: Shuffle, weight: 'bold' },
    broom: { icon: Broom, weight: 'fill' },
    yoga_woman: { icon: PersonSimpleThrow, weight: 'fill' },
    simple_check: { icon: Check, weight: 'bold' },
    cross_mark: { icon: XCircle, weight: 'fill' },
    prohibited: { icon: Prohibition, weight: 'fill' },
    dizzy_star: { icon: Sparkle, weight: 'fill' },
    robot_celebration: { icon: Robot, weight: 'fill' },
    red_heart: { icon: Heart, weight: 'fill' },
    double_checkmark: { icon: Checks, weight: 'bold' },
    card_dividers: { icon: ClipboardText, weight: 'fill' },
    scarf: { icon: HandPalm, weight: 'fill' },
    family_parents_daughter: { icon: UsersFour, weight: 'fill' },
    keycap_number: { icon: ListChecks, weight: 'bold' },
    variation_selector: { icon: null, weight: null }, // invisible unicode, no icon needed
    briefcase: { icon: Briefcase, weight: 'fill' },
    hospital: { icon: FirstAid, weight: 'fill' },
    bandaid: { icon: FirstAid, weight: 'fill' },
    chess: { icon: GameController, weight: 'fill' },
    no_phone: { icon: DeviceMobileCamera, weight: 'fill' },
    balance_scale: { icon: Scales, weight: 'fill' },
    family: { icon: UsersFour, weight: 'fill' },
    teacher: { icon: Chalkboard, weight: 'fill' },
    shopping_cart: { icon: CreditCard, weight: 'fill' },
    classical_building: { icon: Buildings, weight: 'fill' },
    number_one: { icon: null, weight: null }, // numeric, render as text
    number_two: { icon: null, weight: null },
    number_three: { icon: null, weight: null },
    number_four: { icon: null, weight: null },
    heartbeat: { icon: Heartbeat, weight: 'fill' },
    chef: { icon: CookingPot, weight: 'fill' },
};

export default phosphorIconMap;
